name: Deploy to Remote

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20  # 適切なNode.jsバージョンを指定

      - name: Install dependencies and build
        run: |
          yarn install
          yarn build

      - name: Deploy to Remote
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_USER: mantis
          REMOTE_HOST: murais.net
          REMOTE_PATH: /home/xs739875/murais.net/public_html/mantis/
        run: |
          # SSHエージェントを設定
          eval "$(ssh-agent -s)"
          
          # SSH秘密鍵を追加
          echo "$SSH_PRIVATE_KEY" | ssh-add -

          # SSH接続をテスト
          ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 10022 $REMOTE_USER@$REMOTE_HOST

          # rsyncを使用してデプロイ
          rsync -avz --delete --exclude .htaccess ./dist/ $REMOTE_USER@$REMOTE_HOST:$REMOTE_PATH


# name: deploy to xserver

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#         - uses: actions/checkout@v2
#         - uses: borales/actions-yarn@v2.3.0
#           with:
#             cmd: install
#         - uses: borales/actions-yarn@v2.3.0
#           with:
#             cmd: build
#         - name: ssh key generate
#           run: echo "$SSH_PRIVATE_KEY" > key && chmod 600 key
#           env:
#             SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
#         - name: rsync deployments
#           uses: burnett01/rsync-deployments@5.1
#           with:
#             switches: -avz --delete
#             # path: dist/
#             remote_path: /home/xs739875/murais.net/public_html/mantis/
#             remote_host: sv14591.xserver.jp
#             remote_user: mantis@murais.net
#             remote_port: 10022
#             remote_key: ${{ secrets.SSH_PRIVATE_KEY }}

            
# name: deploy to remote

# on:
#   push:
#     branches:
#       - main  # プッシュをトリガーするブランチを指定

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v1
#       - name: gulp build
#         uses: actions/setup-node@v1
#         with:
#           node-version: 20  # 使用するNode.jsバージョンを指定
#       - run: yarn install && yarn build
#       - name: ssh key generate
#         run: echo "$SSH_PRIVATE_KEY" > key && chmod 600 key
#         env:
#           SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
#       - name: rsync deploy
#         run: rsync -auzrv -e "ssh -i key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 10022" --delete ./dist/* mantis@murais.net:/home/xs739875/murais.net/public_html/mantis/ --exclude .htaccess        



# name: deploy to remote

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - name: Setup Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: 20  # または適切なNode.jsバージョンを指定
#       - run: yarn install && yarn build
#       - name: SSH key generate
#         run: |
#           echo "$SSH_PRIVATE_KEY" > key
#           chmod 600 key
#         env:
#           SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
#       - name: Start SSH agent
#         run: eval $(ssh-agent -s)
#       - name: Add SSH private key
#         run: ssh-add key
#       - name: Check SSH Connection
#         run: ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 10022 ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}
#       - name: rsync deploy
#         run: |
#           rsync -avz --delete \
#             --exclude .htaccess \
#             ./dist/ \
#             ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:${{ secrets.REMOTE_PATH }}/
#         env:
#           REMOTE_USER: mantis
#           REMOTE_HOST: murais.net
#           REMOTE_PATH: /home/xs739875/murais.net/public_html/mantis/
#         run: rsync -auzrv -e "ssh -i key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 10022" --delete ./dist/* mantis@murais.net:/home/xs739875/murais.net/public_html/mantis/ --exclude .htaccess
