name: deploy to remote

on:
  push:
    branches:
      - main  # プッシュをトリガーするブランチを指定

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: gulp build
        uses: actions/setup-node@v1
        with:
          node-version: 20  # 使用するNode.jsバージョンを指定
      - run: yarn install && yarn build
      - name: ssh key generate
        run: echo "$SSH_PRIVATE_KEY" > key && chmod 600 key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Deploy with rsync
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p 10022 murais.net >> ~/.ssh/known_hosts
          rsync -auzrv -e "ssh -i ~/.ssh/id_rsa -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 10022" --delete ./dist/* mantis@murais.net:/home/xs739875/murais.net/public_html/mantis/ --exclude .htaccess
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    
