name: deploy to remote

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js 20.6.0
        run: |
          curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
          sudo apt-get install -y nodejs
          node --version  # インストールされたNode.jsバージョンを確認
          npm --version   # インストールされたnpmバージョンを確認
          
      # - name: Install Node.js 20.6.0
      #   run: |
      #     curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
      #     sudo apt-get install -y nodejs
          
      # - name: gulp build
      #   uses: actions/setup-node@v2
      #   with:
      #     # node-version: 20
      #     node-version: 16
          
      - run: yarn install && yarn build
      - name: ssh key generate
        run: |
          echo "$SSH_PRIVATE_KEY" > key
          chmod 600 key
          cat key  # デバッグのために秘密鍵を表示
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: rsync deploy
        run: |
          ssh -i key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 10022 -vvv xs739875@sv14591.xserver.jp echo "SSH connection successful"
          rsync -auzrv -e "ssh -i key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 10022" --delete ./* xs739875@sv14591.xserver.jp:/home/xs739875/murais.net/public_html/mantis/ --exclude .htaccess
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
